apiVersion: v1
kind: Service
metadata:
  name: playground-service
spec:
  type: NodePort # Dışarıdan erişim için NodePort kullanıyoruz
  selector:
    app: playground
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 30080 # Sabit bir port belirliyoruz
